POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Admin",
    "email": "admin@user.com",
    "password": "admin",
    "role": "ADMIN"
}
###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Reader",
    "email": "reader@user.com",
    "password": "admin",
    "role": "READER"
}
###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "name": "Writer",
    "email": "writer@user.com",
    "password": "admin",
    "role": "WRITER"
}

###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{tokenRead}}
{
    "name": "Editor",
    "email": "editor@user.com",
    "password": "admin",
    "role": "EDITOR"
}
###
GET http://localhost:3000/users
Authorization: Bearer {{tokenAdmin}}
###
GET http://localhost:3000/users/cm918fhjp0000uxb0cu4ohxke

###
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
@tokenAdmin = {{ adminLogin.response.body.access_token }} 
###
# @name readLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "reader@user.com",
    "password": "admin"
}

###
@tokenRead = {{ readLogin.response.body.access_token }} 
###

POST http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}
{
    "title": "My first post",
    "content": "This is the content of my first post.",
    "published": true
}

###
GET http://localhost:3000/post
Authorization: Bearer {{tokenAdmin}}
###